coverage:
  status:
    project:
      default:
        target: 100%  # Require 100% overall coverage
        threshold: 0%
        informational: false

ignore:
  - "Baubit.Traceability.Tests/**"  # Exclude test project from coverage calculations
  - "**/*.Tests/**"                  # Extra safety for any test patterns
  - "**/obj/**"                      # Ignore build artifacts
  - "**/bin/**"
